export const USER_AUTHENTICATED_START = "USER_AUTHENTICATED_START";
export const USER_AUTHENTICATED_SUCCESS = "USER_AUTHENTICATED_SUCCESS";
export const USER_AUTHENTICATED_ERROR = "USER_AUTHENTICATED_ERROR";

export const GET_CURRENTUSER_START = "GET_CURRENTUSER_START";
export const GET_CURRENTUSER_SUCCESS = "GET_CURRENTUSER_SUCCESS";
export const GET_CURRENTUSER_ERROR = "GET_CURRENTUSER_ERROR";

export const USER_AUTHENTICATED_START_FB = "USER_AUTHENTICATED_START_FB";
export const USER_AUTHENTICATED_ERROR_FB = "USER_AUTHENTICATED_ERROR_FB";
export const USER_AUTHENTICATED_SUCCESS_FB = "USER_AUTHENTICATED_SUCCESS_FB";
