
export const USER_AUTHENTICATED_START = "USER_AUTHENTICATED_START";
export const USER_AUTHENTICATED_SUCCESS = "USER_AUTHENTICATED_SUCCESS";
export const USER_AUTHENTICATED_ERROR = "USER_AUTHENTICATED_ERROR";
